#serve per far partire più cose, in questo caso facciamo partire sia un docker per il backend sia un docker per postgres
#ricordarsi di ammazzare il postgres locale sennò c'è un conflitto

version: '3'

services:
  dbpostgresql: #servizio1 (inventato da noi, deve coincidere con quello nel application.properties)
    image: "postgres"  #nome fisso di postgres, non inventato
    ports:
      - "5432"
    environment: #variabili di ambiente
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app: #servizio2, il nostro container, quello che abbiamo creato nel dockerfile, il backend
    build: .
    image: appbootrest #nome del jat che verrà mandato in esecuzione, deve coincidere con quello nel dockerfile
    container_name: seabook
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql