apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: booking
  name: booking
spec:
  ports:
    - name: "7500"
      port: 7500
      targetPort: 7500
  selector:
    io.kompose.service: booking
status:
  loadBalancer: {}
