apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: booking
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: booking
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/front_default: "true"
        io.kompose.service: booking
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery:8761/eureka/
          image: artorias94/booking
          name: booking
          ports:
            - containerPort: 7500
          resources: {}
      restartPolicy: Always
status: {}
