apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: discovery
    spec:
      containers:
        - env:
            - name: eureka.client.serviceUrl.defaultZone
              value: http://discovery:8761/eureka/
          image: artorias94/discovery
          name: discovery
          ports:
            - containerPort: 8761
          resources: {}
      restartPolicy: Always
status: {}
