apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: fe
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fe
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/front_default: "true"
        io.kompose.service: fe
    spec:
      containers:
        - image: fe-dev
          imagePullPolicy: Never                                            
          name: fe
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
